name: Test on PR branch
on: pull_request

jobs:
  test-on-per-branch:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 #v7.0.0
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install playwright browsers
        run: npx playwright install chromium

      - name: Run unit tests
        run: npm run-script test
